POST https://8080-marcoweb-apidata2024030-1q4rejtpkdq.ws-us108.gitpod.io/filmes
Content-Type: application/json

{
    "titulo": "Exemplo Novo",
    "sinopse": "Teste de POST Novo",
    "idDiretor": 1
}